name: minishell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make libreadline-dev valgrind clang-tools
        pip install norminette==3.3.55
    - name: Run norminette
      run: norminette
    - name: Compile and static analysis
      run: scan-build --status-bugs make
