name: minishell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install norminette
      run: pip install norminette==3.3.55
    - name: Run norminette
      run: norminette
    - name: Compile
      run: make
